#!/bin/bash

if [ -z "$1" ]
  then echo "Please provide the name of the game, e.g.  ./run_cpu breakout "; exit 0
fi
ENV=$1
FRAMEWORK="alewrap"		# name of training framework

game_path=$PWD"/roms/"		# path to environment file (ROM)
env_params="useRGB=true"	# string of environment parameters
agent="NeuralQLearner"		# name of the file to use
n_replay=1
if [ $# -eq 2 ]; then
	
	#netfile="\"/tmp/trained_networks/DQN3_0_1_"$1"_FULL_Y_"
	#md=`date +%m%d $md`
	#netfile+=$md
	#netfile+=".t7\"" 
	netfile="\"/tmp/trained_networks/DQN3_0_1_"$1"_FULL_Y_0401.t7"
else 
	#netfile="\"convnet_atari3\""
	netfile="\"convnet_paper1\""
fi
update_freq=4
actrep=4			# how many times to repear action
discount=0.99
seed=1				# fixed input seed for repeteable experiments
learn_start=50000
pool_frms_type="\"max\""
pool_frms_size=2
initial_priority="false"
replay_memory=1000000
eps_end=0.1
eps_endt=replay_memory
lr=0.00025
agent_type="DQN3_0_1"
preproc_net="\"net_downsample_2x_full_y\""
agent_name=$agent_type"_"$1"_FULL_Y"	# filename used for saving network
state_dim=7056
ncols=1
agent_params="lr="$lr",ep=1,ep_end="$eps_end",ep_endt="$eps_endt",discount="$discount",hist_len=4,learn_start="$learn_start",replay_memory="$replay_memory",update_freq="$update_freq",n_replay="$n_replay",network="$netfile",preproc="$preproc_net",state_dim="$state_dim",minibatch_size=32,rescale_r=1,ncols="$ncols",bufferSize=512,valid_size=500,target_q=10000,clip_delta=1,min_reward=-1,max_reward=1"		# string of the agent parameters
steps=50000000			# number of training steps to perform
eval_freq=250000		# frequency of greedy evaluation
eval_steps=125000		# number of evaluation steps
prog_freq=10000			# saves the agent network in a separate file
save_freq=125000		# the model is saved every save_freq steps
gpu=0				# gpu flag
random_starts=30		# play action 0 between 1 and random starts number of times at the start of each training episode
pool_frms="type="$pool_frms_type",size="$pool_frms_size		# string of frame pooling parameters
num_threads=4
display=0			# 1 to enable display

args="-framework $FRAMEWORK -game_path $game_path -name $agent_name -env $ENV -env_params $env_params -agent $agent -agent_params $agent_params -steps $steps -eval_freq $eval_freq -eval_steps $eval_steps -prog_freq $prog_freq -save_freq $save_freq -actrep $actrep -gpu $gpu -random_starts $random_starts -pool_frms $pool_frms -seed $seed -threads $num_threads -display $display"
#echo $args

cd dqn
if [ display ]; then 
	../torch/bin/qlua train_agent.lua $args;
else
	../torch/bin/luajit train_agent.lua $args;
fi

